FROM python:3.9
WORKDIR /workspace

COPY extra/meteo/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY settings.json settings.json
COPY extra/meteo meteo

CMD ["python3", "-m", "meteo"]
