version: '3.0'

services:
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - '3000:3000'
    networks:
      - iot
    environment:
      GF_INSTALL_PLUGINS: grafana-image-renderer
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    depends_on:
      - influx
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    networks:
      - iot
  influx:
    image: influxdb:latest
    ports:
      - '8086:8086'
    networks:
      - iot
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup   
      DOCKER_INFLUXDB_INIT_USERNAME: simone    
      DOCKER_INFLUXDB_INIT_PASSWORD: hPkVy7HgYfhLB98    
      DOCKER_INFLUXDB_INIT_ORG: iot   
      DOCKER_INFLUXDB_INIT_BUCKET: data    
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: JFw6cD7sciRoVX1vjrj8nfC8hahAYAN3-mlplIfnTzU2OGezVBQh9nDQMILqzdGr_88UFo0lHXQ7pP
                                
networks:
  iot:
    driver: bridge