{
 "title": "IoT",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temp + predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"env\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n"
    },
    {
     "query": " from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forecast_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"yhat\")"
    }
   ]
  },
  {
   "title": "Hum + predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"env\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n"
    },
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forecast_humidity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"yhat\")\n"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"data\" and\n    r._field == \"rssi\"\n  )"
    }
   ]
  },
  {
   "title": "Gas Concentration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"env\" and\n    r._field == \"gas_concentration\"\n  )"
    },
    {
     "query": " from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forecast_gas_concentration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"yhat\")"
    }
   ]
  },
  {
   "title": "AQI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"env\" and\n    r._field == \"aqi\"\n  )"
    }
   ]
  },
  {
   "title": "Extra - Meteostat Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"extra\" and\n    r._field == \"temperature\"\n  )"
    }
   ]
  }
 ]
}